#数据库相关配置
spring:
  datasource:
    dynamic: 
      type: com.alibaba.druid.pool.DruidDataSource
      primary: master 
      druid:
        #初始化连接池大小
        initial-size: 5
        #配置最小连接数
        min-idle: 5
        #配置最大连接数
        max-active: 20
        #配置连接等待超时时间
        max-wait: 60000
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        time-between-eviction-runs-millis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        min-evictable-idle-time-millis: 300000
        #测试连接
        validation-query: SELECT 1 FROM DUAL
        #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全
        test-while-idle: true
        #获取连接时执行检测，建议关闭，影响性能
        test-on-borrow: false
        #归还连接时执行检测，建议关闭，影响性能
        test-on-return: false
        #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
        pool-prepared-statements: true
        #开启poolPreparedStatements后生效
        max-pool-prepared-statement-per-connection-size: 20
        #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
        filters: stat,wall,slf4j
    druid: 
      #打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      #配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      #配置DruidStatViewServlet
      stat-view-servlet:
        enabled: true
        url-pattern: "/druid/*"
        #IP白名单(没有配置或者为空，则允许所有访问)
        #allow: 127.0.0.1,192.168.163.1
        #IP黑名单 (存在共同时，deny优先于allow)
        #deny: 192.168.1.73
        # 禁用HTML页面上的“Reset All”功能
        reset-enable: false
        #登录名
        login-username: root
        #登录密码
        login-password: root
# redis配置
  redis:
    timeout: 15000
    jedis:
      pool:
        max-active: 1024
        max-idle: 200
        max-wait: 1500
        min-idle: 0
        

# mybatis- plus配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号隔开隔开
  mapper-locations: classpath:mapper/*.xml
  #扫描实体类
  ype-aliases-package: com.yysh.hstadmin.entity
  # 以下配置均有默认值,可以不设置
  global-config:
    db-config:
      #主键类型 AUTO:"数据库ID自增" INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  configuration:
    # 是否开启自动驼峰命名规则映射:从数据库列名到Java属性驼峰命名的类似映射
    map-underscore-to-camel-case: true
    # 返回map时true:当查询数据为空时字段返回为null,false:不加这个查询数据为空时，字段将被隐藏
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   
    
